#!/bin/bash
# ============================================================
# collect_paper_figures.sh
# Collects all paper figures from HPC results directories
# and copies them to a single folder for download.
#
# Run from: ~/Documents/arcede_dmdhp_paper
# Usage: bash collect_paper_figures.sh
# ============================================================

OUTDIR="paper_figures"
mkdir -p "$OUTDIR"

echo "============================================================"
echo "  Collecting DMDHP paper figures"
echo "============================================================"

# ── Figure 1: Productivity ratio plot (already generated) ────
if [ -f "ph_results/productivity_ratio_plot.png" ]; then
    cp ph_results/productivity_ratio_plot.png "$OUTDIR/Fig1_productivity_ratio.png"
    echo "  Fig1: productivity_ratio_plot.png ✅"
else
    echo "  Fig1: NOT FOUND — will be generated by plot script"
fi

# ── Figure 2: PIT diagnostics for Hinatuan ───────────────────
if [ -d "ph_results/pit_diagnostics" ]; then
    # Find Hinatuan PIT files
    for f in ph_results/pit_diagnostics/*Hinatuan* ph_results/pit_diagnostics/*hinatuan* \
              ph_results/pit_diagnostics/*SEQ1*; do
        [ -f "$f" ] && cp "$f" "$OUTDIR/" && echo "  PIT file: $(basename $f) ✅"
    done
    # List all available PIT files
    echo ""
    echo "  All available PIT files:"
    ls ph_results/pit_diagnostics/ 2>/dev/null | sed 's/^/    /'
else
    echo "  pit_diagnostics/: NOT FOUND"
fi

# ── MC results figures ────────────────────────────────────────
for f in mc_results/*.png mc_results/**/*.png; do
    [ -f "$f" ] && cp "$f" "$OUTDIR/" && echo "  MC fig: $(basename $f) ✅"
done

# ── List final contents ───────────────────────────────────────
echo ""
echo "============================================================"
echo "  Files collected to ./$OUTDIR/"
echo "============================================================"
ls -lh "$OUTDIR/"
echo ""
echo "Next: run python3 generate_paper_figures.py to create"
echo "any missing figures."
